### ISSUE TITLE
Fix outdated build tooling

### ISSUE THREAD

**Issue by santhoshtr** [Lorti/vue-dictaphone#14]
This library uses slightly complicated  build using webpack configurations and many unwanted devDependencies. For example node-sass is unnecessary as there is no sass requirement and installing it require compiling C code in target  machine. Many of dev-dependencies are old versions.

I propose building it using vue-cli and simplify the build tooling and configuration.

I will help modernizing the library.

**Comment by Lorti** [comment]
Yes, it’s a 2 years old project built with the now deprecated Vue CLI 2. Thank you for your time!
