### ISSUE TITLE
Version 1.3.0 is broken

### ISSUE THREAD

**Issue by santhoshtr** [Lorti/vue-dictaphone#16]
https://www.npmjs.com/package/vue-dictaphone/v/1.3.0 does not contain dist folder. Possibly because of issue #14 ?

**Comment by Lorti** [comment]
Sorry for that. I think the repository needs a `prepublish` script. I will add it after merge your pull request #15 .

**Comment by Lorti** [comment]
Is `vue-dictaphone@2.0.0` working for you now?

**Comment by santhoshtr** [comment]
Works fine for me. Thanks!
