### ISSUE TITLE
How to lossless record?

### ISSUE THREAD

**Issue by vzxxbacq** [Lorti/vue-dictaphone#7]
Hello @Lorti , I set `mime-type="audio/wav"` when I try to record audio losslessly, but the audios seem to be compressed. Can I record audio losslessly by vue-dictaphone? Thank you!

**Comment by Lorti** [comment]
Where have you tried recording the audio? Not every browser supports the same media types. If MDN is correct then `audio/wav` is not supported in Chrome: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#WAVE_PCM
There is also a compatibility table there. Hope this helps you!
